name: fff
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.4
  share: ^2.0.4
  shared_preferences: ^2.0.11
  google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.jpg
    - assets/images/point.png
    - assets/images/emotes/Applause.png
    - assets/images/emotes/Babyshark.png
    - assets/images/emotes/Bhangra.png
    - assets/images/emotes/Lol.png
    - assets/images/emotes/Provoke.png
    - assets/images/emotes/OneFin.png
    - assets/images/trending/BlueCriminal.png
    - assets/images/trending/RedCriminal.png
    - assets/images/trending/GreenCriminal.png
    - assets/images/trending/YellowCriminal.png
    - assets/images/trending/HiphopCriminal.png
    - assets/images/trending/RedSamurai.png
    - assets/images/guns/ak.png
    - assets/images/guns/AWM.png
    - assets/images/guns/s.png
    - assets/images/guns/s2.png
    - assets/images/guns/scar.png
    - assets/images/guns/shot.png
    - assets/images/events/1.png
    - assets/images/events/2.png
    - assets/images/events/3.png
    - assets/images/events/4.png
    - assets/images/home/tre.png
    - assets/images/home/gun.png
    - assets/images/home/pro.png
    - assets/images/home/rare.png
    - assets/images/home/refer.png
    - assets/images/home/how.png
    - assets/images/incubator/incubator1.png
    - assets/images/incubator/incubator2.png
    - assets/images/incubator/incubator3.png
    - assets/images/incubator/incubator4.png
    - assets/images/incubator/incubator5.png
    - assets/images/incubator/incubator6.png
    - assets/images/season/1.png
    - assets/images/season/2.png
    - assets/images/season/3.png
    - assets/images/season/4.png
    - assets/images/season/5.png
    - assets/images/season/6.png
    - assets/images/season/7.png
    - assets/images/season/8.png
    - assets/images/pd/1.png
    - assets/images/pd/2.png
    - assets/images/pd/3.png
    - assets/images/pd/4.png
    - assets/images/home/1.png
    - assets/images/home/2.png
    - assets/images/home/3.png
    - assets/images/home/4.png
    - assets/images/home/5.png
    - assets/images/home/6.png
    - assets/images/home/banner.png
    - assets/images/a.png
    - assets/images/bgimage.png
    - assets/images/round.png
    - assets/images/share.png
    - assets/images/bgimage.jpg
    - assets/images/sharei.png
    - assets/images/launch.png
    - assets/images/playstore.png
    - assets/images/end.png
    - assets/images/activate.png
    #sdkksdjionsdo - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", seew
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
        - asset: assets/fonts/Muli-Light.ttf
        - asset: assets/fonts/Muli-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
